version: "3"

services:
  app1:
    container_name: websocket-client1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    volumes:
      - .:/app
  app2:
    container_name: websocket-client2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8080"
    volumes:
      - .:/app
  app3:
    container_name: websocket-client3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8080"
    volumes:
      - .:/app